import type { PipelineCandidate } from "./types";

const CRITERIA = [
  "3+ years ML/AI experience",
  "Open-source contributions",
  "Startup experience",
] as const;

export const CRITERION_LABELS = CRITERIA;

export const mockCandidates: PipelineCandidate[] = [
  // 4 assessed + fit
  {
    id: "c-001",
    name: "Elena Rodriguez",
    headline: "Senior ML Engineer at DeepScale AI",
    location: "San Francisco, CA",
    avatar: "ER",
    skills: ["PyTorch", "Transformers", "MLOps", "Kubernetes", "Python"],
    yearsExperience: 7,
    status: "assessed",
    outcome: "fit",
    criteria: [
      { criterion: CRITERIA[0], met: true, reasoning: "7 years building production ML pipelines at DeepScale AI and prior roles at Google Brain." },
      { criterion: CRITERIA[1], met: true, reasoning: "Core contributor to Hugging Face Transformers with 48 merged PRs." },
      { criterion: CRITERIA[2], met: true, reasoning: "First ML hire at DeepScale AI (Series A), scaled team from 1 to 12." },
    ],
    summary: "Exceptional ML engineer with deep production experience and strong open-source track record.",
    email: "elena.r@deepscale.ai",
    startupVibe: null,
  },
  {
    id: "c-002",
    name: "Marcus Chen",
    headline: "AI Research Lead at Nexus Labs",
    location: "Seattle, WA",
    avatar: "MC",
    skills: ["TensorFlow", "NLP", "Computer Vision", "Rust", "CUDA"],
    yearsExperience: 9,
    status: "assessed",
    outcome: "fit",
    criteria: [
      { criterion: CRITERIA[0], met: true, reasoning: "9 years in AI research, published 12 papers at top conferences (NeurIPS, ICML)." },
      { criterion: CRITERIA[1], met: true, reasoning: "Created and maintains `fast-attention` library with 3.2k GitHub stars." },
      { criterion: CRITERIA[2], met: true, reasoning: "Co-founded Nexus Labs, raised $4.2M seed round." },
    ],
    summary: "Research-oriented leader who bridges academia and production with proven startup DNA.",
    email: "marcus@nexuslabs.io",
    startupVibe: null,
  },
  {
    id: "c-003",
    name: "Priya Sharma",
    headline: "ML Platform Engineer at Databricks",
    location: "Austin, TX",
    avatar: "PS",
    skills: ["Spark MLlib", "Feature Stores", "Python", "Scala", "AWS"],
    yearsExperience: 5,
    status: "assessed",
    outcome: "fit",
    criteria: [
      { criterion: CRITERIA[0], met: true, reasoning: "5 years building ML infrastructure at Databricks and previous role at Stripe." },
      { criterion: CRITERIA[1], met: true, reasoning: "Maintains popular MLflow plugin with 800+ stars, active contributor to Apache Spark." },
      { criterion: CRITERIA[2], met: true, reasoning: "Early engineer (#8) at ML startup acquired by Databricks in 2022." },
    ],
    summary: "Strong ML platform background with acquisition experience and active OSS contributions.",
    email: "priya.s@databricks.com",
    startupVibe: null,
  },
  {
    id: "c-004",
    name: "James Okafor",
    headline: "CTO at VeridAI (YC W23)",
    location: "New York, NY",
    avatar: "JO",
    skills: ["LLMs", "RAG", "System Design", "Go", "Python"],
    yearsExperience: 8,
    status: "assessed",
    outcome: "fit",
    criteria: [
      { criterion: CRITERIA[0], met: true, reasoning: "8 years in AI, including 3 years leading LLM product development at VeridAI." },
      { criterion: CRITERIA[1], met: true, reasoning: "Open-sourced VeridAI's RAG framework, 5.1k stars. Regular conference speaker." },
      { criterion: CRITERIA[2], met: true, reasoning: "CTO and co-founder of VeridAI (YC W23), grew to 40 employees." },
    ],
    summary: "YC-backed founder with deep LLM expertise and proven ability to scale teams.",
    email: "james@veridai.com",
    startupVibe: null,
  },
  // 3 assessed + rejected
  {
    id: "c-005",
    name: "Sarah Kim",
    headline: "Data Scientist at Walmart Labs",
    location: "Bentonville, AR",
    avatar: "SK",
    skills: ["R", "SQL", "Tableau", "Python", "Statistics"],
    yearsExperience: 4,
    status: "assessed",
    outcome: "rejected",
    criteria: [
      { criterion: CRITERIA[0], met: true, reasoning: "4 years in data science with ML model deployment experience." },
      { criterion: CRITERIA[1], met: false, reasoning: "No public GitHub profile or open-source contributions found." },
      { criterion: CRITERIA[2], met: false, reasoning: "Entire career at large enterprises (Walmart, Deloitte). No startup experience." },
    ],
    summary: "Solid data scientist but lacks open-source and startup background.",
    email: "sarah.kim@walmart.com",
    startupVibe: null,
  },
  {
    id: "c-006",
    name: "Alex Petrov",
    headline: "Junior ML Engineer at IBM",
    location: "Toronto, Canada",
    avatar: "AP",
    skills: ["Scikit-learn", "Pandas", "Python", "Docker"],
    yearsExperience: 2,
    status: "assessed",
    outcome: "rejected",
    criteria: [
      { criterion: CRITERIA[0], met: false, reasoning: "Only 2 years of experience, primarily in model evaluation rather than development." },
      { criterion: CRITERIA[1], met: false, reasoning: "GitHub shows personal projects only, no contributions to established repositories." },
      { criterion: CRITERIA[2], met: false, reasoning: "No startup experience. Career has been at IBM." },
    ],
    summary: "Too early in career for senior role requirements. Revisit in 2-3 years.",
    email: "apetrov@ibm.com",
    startupVibe: null,
  },
  {
    id: "c-007",
    name: "Diana Foster",
    headline: "Machine Learning Engineer at Netflix",
    location: "Los Gatos, CA",
    avatar: "DF",
    skills: ["Recommendation Systems", "A/B Testing", "Python", "Java", "Spark"],
    yearsExperience: 6,
    status: "assessed",
    outcome: "rejected",
    criteria: [
      { criterion: CRITERIA[0], met: true, reasoning: "6 years in ML, specializing in recommendation systems at Netflix and Spotify." },
      { criterion: CRITERIA[1], met: false, reasoning: "No open-source contributions. Work has been proprietary." },
      { criterion: CRITERIA[2], met: true, reasoning: "Spent 2 years at a music-tech startup before joining Spotify." },
    ],
    summary: "Strong ML engineer but no open-source presence is a concern for the role.",
    email: "diana.f@netflix.com",
    startupVibe: null,
  },
  // 3 assessing
  {
    id: "c-008",
    name: "Raj Patel",
    headline: "Senior AI Engineer at Anthropic",
    location: "San Francisco, CA",
    avatar: "RP",
    skills: ["RLHF", "Constitutional AI", "Python", "JAX", "Alignment"],
    yearsExperience: 6,
    status: "assessing",
    outcome: null,
    criteria: [
      { criterion: CRITERIA[0], met: true, reasoning: "6 years in AI safety and alignment research." },
      { criterion: CRITERIA[1], met: null, reasoning: null },
      { criterion: CRITERIA[2], met: null, reasoning: null },
    ],
    summary: "Currently evaluating open-source and startup criteria...",
    email: "raj.p@anthropic.com",
    startupVibe: null,
  },
  {
    id: "c-009",
    name: "Lisa Zhang",
    headline: "ML Ops Lead at Stripe",
    location: "Remote, US",
    avatar: "LZ",
    skills: ["MLOps", "Kubernetes", "Airflow", "Python", "Terraform"],
    yearsExperience: 5,
    status: "assessing",
    outcome: null,
    criteria: [
      { criterion: CRITERIA[0], met: null, reasoning: null },
      { criterion: CRITERIA[1], met: null, reasoning: null },
      { criterion: CRITERIA[2], met: null, reasoning: null },
    ],
    summary: "Assessment in progress...",
    email: "lzhang@stripe.com",
    startupVibe: null,
  },
  {
    id: "c-010",
    name: "Tom Wilson",
    headline: "AI Product Manager at OpenAI",
    location: "San Francisco, CA",
    avatar: "TW",
    skills: ["Product Strategy", "LLMs", "Python", "SQL", "Figma"],
    yearsExperience: 4,
    status: "assessing",
    outcome: null,
    criteria: [
      { criterion: CRITERIA[0], met: true, reasoning: "4 years working directly with ML teams, hands-on with fine-tuning." },
      { criterion: CRITERIA[1], met: true, reasoning: "Maintains an open-source LLM evaluation toolkit." },
      { criterion: CRITERIA[2], met: null, reasoning: null },
    ],
    summary: "Two criteria assessed so far, both positive. Checking startup experience...",
    email: "tom@openai.com",
    startupVibe: null,
  },
  // 4 pending
  {
    id: "c-011",
    name: "Nina Kowalski",
    headline: "Research Scientist at Meta FAIR",
    location: "Menlo Park, CA",
    avatar: "NK",
    skills: ["Computer Vision", "GANs", "PyTorch", "C++", "CUDA"],
    yearsExperience: 7,
    status: "pending",
    outcome: null,
    criteria: [
      { criterion: CRITERIA[0], met: null, reasoning: null },
      { criterion: CRITERIA[1], met: null, reasoning: null },
      { criterion: CRITERIA[2], met: null, reasoning: null },
    ],
    summary: "Queued for assessment.",
    email: "nina.k@meta.com",
    startupVibe: null,
  },
  {
    id: "c-012",
    name: "David Nakamura",
    headline: "Founding Engineer at SynthML",
    location: "Tokyo, Japan",
    avatar: "DN",
    skills: ["Generative AI", "Diffusion Models", "Python", "TypeScript", "React"],
    yearsExperience: 5,
    status: "pending",
    outcome: null,
    criteria: [
      { criterion: CRITERIA[0], met: null, reasoning: null },
      { criterion: CRITERIA[1], met: null, reasoning: null },
      { criterion: CRITERIA[2], met: null, reasoning: null },
    ],
    summary: "Queued for assessment.",
    email: "david@synthml.io",
    startupVibe: null,
  },
  {
    id: "c-013",
    name: "Maria Santos",
    headline: "Senior SWE at Google DeepMind",
    location: "London, UK",
    avatar: "MS",
    skills: ["Reinforcement Learning", "TensorFlow", "Python", "Go", "Distributed Systems"],
    yearsExperience: 8,
    status: "pending",
    outcome: null,
    criteria: [
      { criterion: CRITERIA[0], met: null, reasoning: null },
      { criterion: CRITERIA[1], met: null, reasoning: null },
      { criterion: CRITERIA[2], met: null, reasoning: null },
    ],
    summary: "Queued for assessment.",
    email: "msantos@deepmind.com",
    startupVibe: null,
  },
  {
    id: "c-014",
    name: "Chris Andersson",
    headline: "ML Engineer at Spotify",
    location: "Stockholm, Sweden",
    avatar: "CA",
    skills: ["Audio ML", "PyTorch", "Python", "Scala", "GCP"],
    yearsExperience: 4,
    status: "pending",
    outcome: null,
    criteria: [
      { criterion: CRITERIA[0], met: null, reasoning: null },
      { criterion: CRITERIA[1], met: null, reasoning: null },
      { criterion: CRITERIA[2], met: null, reasoning: null },
    ],
    summary: "Queued for assessment.",
    email: "chris.a@spotify.com",
    startupVibe: null,
  },
];
