import { LINKEDIN_ALLOWED_DOMAINS } from "@/agents/linkedin/query";

export const LINKEDIN_POSTS_ALLOWED_DOMAINS = LINKEDIN_ALLOWED_DOMAINS;
export const LINKEDIN_POSTS_ANALYSIS_LIMIT = 3;
export const LINKEDIN_POSTS_DEFAULT_SEARCH_LIMIT = 25;
export const LINKEDIN_POSTS_MAX_SEARCH_LIMIT = 50;
